name: Build images
on: push

env:
  TAG_NAME: 2.7.2-alpine

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build builder image
        working-directory: ./Builder
        run: docker build -t builder .

      - name: Build final image
        working-directory: ./Final
        run: docker build -t final .

      - name: Push the images to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

          docker tag builder ghcr.io/davidbkay/rails-base-builder:latest
          docker tag builder ghcr.io/davidbkay/rails-base-builder:${{ env.TAG_NAME }}
          docker push ghcr.io/davidbkay/rails-base-builder:latest
          docker push ghcr.io/davidbkay/rails-base-builder:${{ env.TAG_NAME }}

          docker tag final ghcr.io/davidbkay/rails-base-final:latest
          docker push ghcr.io/davidbkay/rails-base-final:latest
          docker tag final ghcr.io/davidbkay/rails-base-final:${{ env.TAG_NAME }}
          docker push ghcr.io/davidbkay/rails-base-final:${{ env.TAG_NAME }}

      - name: Push the images to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u davidbkay --password-stdin

          docker tag builder davidbkay/rails-base-builder:latest
          docker push davidbkay/rails-base-builder:latest
          docker tag builder davidbkay/rails-base-builder:${{ env.TAG_NAME }}
          docker push davidbkay/rails-base-builder:${{ env.TAG_NAME }}

          docker tag final davidbkay/rails-base-final:latest
          docker push davidbkay/rails-base-final:latest
          docker tag final davidbkay/rails-base-final:${{ env.TAG_NAME }}
          docker push davidbkay/rails-base-final:${{ env.TAG_NAME }}
